<script type="text/javascript" charset="utf-8">

    $(document).ready(function() {
        $('.site_quick_jump').change(function(){
            
            // option 2; set the 'action' of the form and submit it
            if ($(this).val() != '') {
                $('#site_quick_jump_form').attr('action', '<?php echo $this->baseUrl(); ?>/default/authentication/login/'); // 
                $('#site_quick_jump_form').attr('target', '_self'); // new window
                $('#site_quick_jump_form').submit(); // Go!
            }
        });
    });

</script>    
    
<div class="site_quick_jump_container">
    <form id="site_quick_jump_form" method="get" action="">
    Unidade: <select name="codUnidade" class="site_quick_jump">
                <option></option>
                <?php foreach ($this->unidades as $unidade) { ?>
                <option value="<?php echo $unidade['CodUnidade']; ?>"><?php echo $unidade['Unidade']; ?></option>
                <?php } ?>
           </select>
    </form>
</div>