<!DOCTYPE html>
<html>

  <head>
    <!-- FOLHAS DE ESTILO DO BOOTSTRAP TWITTER -->
    <link href="<?php echo $this->baseUrl(); ?>/css/bootstrap.css" rel="stylesheet">
    <link href="<?php echo $this->baseUrl(); ?>/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="<?php echo $this->baseUrl(); ?>/css/docs.css" rel="stylesheet">
    <link href="<?php echo $this->baseUrl(); ?>/js/google-code-prettify/prettify.css" rel="stylesheet">
  </head>

  <body>
  
  
  <div class="container">
    
        <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
          <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </a>
            
            <a class="brand" href="#">Portal do Aluno</a>
            <div class="nav-collapse">
              <ul class="nav">
                <li><a href="#">Home</a></li>
                <li class="divider-vertical"></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li class="divider"></li>
                    <li><a href="#">Separated link</a></li>
                  </ul>
                </li>
              </ul>

              <ul class="nav pull-right">
                <li><a href="#">Link</a></li>
                <li class="divider-vertical"></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li class="divider"></li>
                    <li><a href="#">Separated link</a></li>
                  </ul>
                </li>
              </ul>
            </div><!-- /.nav-collapse -->
          </div>
        </div><!-- /navbar-inner -->
      </div>
      
      

      <?php echo $this->layout()->content; ?>
 
 
    <!-- JAVASCRIPTS DO BOOTSTRAP TWITTER -->
    <script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/js/jquery.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/js/google-code-prettify/prettify.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/js/bootstrap-transition.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/js/bootstrap-alert.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/js/bootstrap-modal.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/js/bootstrap-dropdown.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/js/bootstrap-scrollspy.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/js/bootstrap-tab.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/js/bootstrap-tooltip.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/js/bootstrap-popover.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/js/bootstrap-button.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/js/bootstrap-collapse.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/js/bootstrap-carousel.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/js/bootstrap-typeahead.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/js/application.js"></script>

    </div>
    
  </body>
	
</html>








